[2024-12-20T17:06:26.003+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T07:58:36+00:00 [queued]>
[2024-12-20T17:06:26.012+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T07:58:36+00:00 [queued]>
[2024-12-20T17:06:26.013+0900] {taskinstance.py:1359} INFO - Starting attempt 4 of 4
[2024-12-20T17:06:26.027+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-20 07:58:36+00:00
[2024-12-20T17:06:26.033+0900] {standard_task_runner.py:57} INFO - Started process 1714 to run task
[2024-12-20T17:06:26.036+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-20T07:58:36+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpwh9ivdnw']
[2024-12-20T17:06:26.039+0900] {standard_task_runner.py:85} INFO - Job 7: Subtask post_crawl
[2024-12-20T17:06:26.083+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T07:58:36+00:00 [running]> on host 8b6312293dda
[2024-12-20T17:06:26.154+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T07:58:36+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T07:58:36+00:00'
[2024-12-20T17:06:26.155+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-20 17:06:26
[2024-12-20T17:06:26.312+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-20T17:06:26.377+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T17:06:26.461+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T17:06:26.552+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-20T17:06:26.585+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1973, in post_main
    jumpit_crawling()
  File "/code/plugins/post_crawling.py", line 171, in jumpit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x565194d788fa <unknown>
#1 0x565194889d20 <unknown>
#2 0x5651948c74c7 <unknown>
#3 0x5651948c1e8f <unknown>
#4 0x5651948bcf96 <unknown>
#5 0x565194908d86 <unknown>
#6 0x5651949083d6 <unknown>
#7 0x5651948fc893 <unknown>
#8 0x5651948cb30d <unknown>
#9 0x5651948cc32e <unknown>
#10 0x565194d4500b <unknown>
#11 0x565194d48f97 <unknown>
#12 0x565194d3171c <unknown>
#13 0x565194d49b17 <unknown>
#14 0x565194d166cf <unknown>
#15 0x565194d676b8 <unknown>
#16 0x565194d67880 <unknown>
#17 0x565194d77776 <unknown>
#18 0x7f1a8ff87ea7 start_thread

[2024-12-20T17:06:26.594+0900] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241220T075836, start_date=20241220T080626, end_date=20241220T080626
[2024-12-20T17:06:26.607+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task post_crawl (Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x565194d788fa <unknown>
#1 0x565194889d20 <unknown>
#2 0x5651948c74c7 <unknown>
#3 0x5651948c1e8f <unknown>
#4 0x5651948bcf96 <unknown>
#5 0x565194908d86 <unknown>
#6 0x5651949083d6 <unknown>
#7 0x5651948fc893 <unknown>
#8 0x5651948cb30d <unknown>
#9 0x5651948cc32e <unknown>
#10 0x565194d4500b <unknown>
#11 0x565194d48f97 <unknown>
#12 0x565194d3171c <unknown>
#13 0x565194d49b17 <unknown>
#14 0x565194d166cf <unknown>
#15 0x565194d676b8 <unknown>
#16 0x565194d67880 <unknown>
#17 0x565194d77776 <unknown>
#18 0x7f1a8ff87ea7 start_thread
; 1714)
[2024-12-20T17:06:26.612+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T17:06:26.633+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
