[2024-12-19T17:51:17.240+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:49:43+00:00 [queued]>
[2024-12-19T17:51:17.252+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:49:43+00:00 [queued]>
[2024-12-19T17:51:17.252+0900] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-19T17:51:17.268+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-19 08:49:43+00:00
[2024-12-19T17:51:17.273+0900] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2024-12-19T17:51:17.277+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-19T08:49:43+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmp000t_zm7']
[2024-12-19T17:51:17.280+0900] {standard_task_runner.py:85} INFO - Job 4: Subtask post_crawl
[2024-12-19T17:51:17.324+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:49:43+00:00 [running]> on host 885d0f0d454c
[2024-12-19T17:51:17.399+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T08:49:43+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T08:49:43+00:00'
[2024-12-19T17:51:17.400+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-19 17:51:17
[2024-12-19T17:51:17.489+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:51:17.564+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:17.656+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:17.732+0900] {logger.py:11} INFO - There is no [linux64] chromedriver "131.0.6778.204" for browser google-chrome "131.0.6778" in cache
[2024-12-19T17:51:17.733+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:18.047+0900] {logger.py:11} INFO - WebDriver version 131.0.6778.204 selected
[2024-12-19T17:51:18.051+0900] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T17:51:18.051+0900] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T17:51:18.245+0900] {logger.py:11} INFO - Driver downloading response is 200
[2024-12-19T17:51:18.834+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:19.052+0900] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204]
[2024-12-19T17:51:19.509+0900] {logging_mixin.py:151} INFO - 점핏 종료 시간: 2024-12-19 17:51:19
[2024-12-19T17:51:29.516+0900] {logging_mixin.py:151} INFO - 원티드 시작 시간: 2024-12-19 17:51:29
[2024-12-19T17:51:29.529+0900] {credentials.py:1254} INFO - Found credentials in shared credentials file: /code/.aws/credentials
[2024-12-19T17:51:29.744+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:51:29.828+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:29.909+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:29.978+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:51:30.287+0900] {logging_mixin.py:151} INFO - 원티드 종료 시간: 2024-12-19 17:51:30
[2024-12-19T17:51:30.287+0900] {logging_mixin.py:151} INFO - 인크루트 시작 시간: 2024-12-19 17:51:30
[2024-12-19T17:51:31.061+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:51:31.124+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:31.203+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:31.268+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:51:31.679+0900] {logging_mixin.py:151} INFO - 인크루트 종료 시간: 2024-12-19 17:51:31
[2024-12-19T17:51:41.690+0900] {logging_mixin.py:151} INFO - 로켓펀치 시작 시간: 2024-12-19 17:51:41
[2024-12-19T17:51:41.777+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:51:41.845+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:41.911+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:41.979+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:51:42.238+0900] {logging_mixin.py:151} INFO - 로켓펀치 종료 시간: 2024-12-19 17:51:42
[2024-12-19T17:51:52.248+0900] {logging_mixin.py:151} INFO - 잡코리아 시작 시간: 2024-12-19 17:51:52
[2024-12-19T17:51:52.419+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:51:52.496+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:52.562+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:51:52.630+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:51:52.923+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1988, in post_main
    jobkorea_crawling()
  File "/code/plugins/post_crawling.py", line 1311, in jobkorea_crawling
    with open('log.txt', 'r') as log_file:
FileNotFoundError: [Errno 2] No such file or directory: 'log.txt'
[2024-12-19T17:51:52.933+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241219T084943, start_date=20241219T085117, end_date=20241219T085152
[2024-12-19T17:51:52.945+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task post_crawl ([Errno 2] No such file or directory: 'log.txt'; 136)
[2024-12-19T17:51:52.982+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-19T17:51:53.002+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
