[2024-12-20T00:01:27.517+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [queued]>
[2024-12-20T00:01:27.525+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [queued]>
[2024-12-20T00:01:27.525+0900] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-20T00:01:27.539+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-18 15:00:00+00:00
[2024-12-20T00:01:27.544+0900] {standard_task_runner.py:57} INFO - Started process 5253 to run task
[2024-12-20T00:01:27.547+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'scheduled__2024-12-18T15:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmp_ma485_j']
[2024-12-20T00:01:27.549+0900] {standard_task_runner.py:85} INFO - Job 8: Subtask post_crawl
[2024-12-20T00:01:27.588+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [running]> on host 885d0f0d454c
[2024-12-20T00:01:27.650+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T15:00:00+00:00'
[2024-12-20T00:01:27.651+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-20 00:01:27
[2024-12-20T00:01:31.738+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-20T00:01:31.854+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T00:01:31.945+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T00:01:32.017+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T00:01:32.341+0900] {logger.py:11} INFO - WebDriver version 131.0.6778.204 selected
[2024-12-20T00:01:32.344+0900] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-20T00:01:32.345+0900] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-20T00:01:32.454+0900] {logger.py:11} INFO - Driver downloading response is 200
[2024-12-20T00:01:32.721+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T00:01:32.801+0900] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204]
[2024-12-20T00:01:32.833+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1969, in post_main
    jumpit_crawling()
  File "/code/plugins/post_crawling.py", line 171, in jumpit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x5636b98bf8fa <unknown>
#1 0x5636b93d0d20 <unknown>
#2 0x5636b940e4c7 <unknown>
#3 0x5636b9408e8f <unknown>
#4 0x5636b9403f96 <unknown>
#5 0x5636b944fd86 <unknown>
#6 0x5636b944f3d6 <unknown>
#7 0x5636b9443893 <unknown>
#8 0x5636b941230d <unknown>
#9 0x5636b941332e <unknown>
#10 0x5636b988c00b <unknown>
#11 0x5636b988ff97 <unknown>
#12 0x5636b987871c <unknown>
#13 0x5636b9890b17 <unknown>
#14 0x5636b985d6cf <unknown>
#15 0x5636b98ae6b8 <unknown>
#16 0x5636b98ae880 <unknown>
#17 0x5636b98be776 <unknown>
#18 0x7f8953a5aea7 start_thread

[2024-12-20T00:01:32.842+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241218T150000, start_date=20241219T150127, end_date=20241219T150132
[2024-12-20T00:01:32.855+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task post_crawl (Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x5636b98bf8fa <unknown>
#1 0x5636b93d0d20 <unknown>
#2 0x5636b940e4c7 <unknown>
#3 0x5636b9408e8f <unknown>
#4 0x5636b9403f96 <unknown>
#5 0x5636b944fd86 <unknown>
#6 0x5636b944f3d6 <unknown>
#7 0x5636b9443893 <unknown>
#8 0x5636b941230d <unknown>
#9 0x5636b941332e <unknown>
#10 0x5636b988c00b <unknown>
#11 0x5636b988ff97 <unknown>
#12 0x5636b987871c <unknown>
#13 0x5636b9890b17 <unknown>
#14 0x5636b985d6cf <unknown>
#15 0x5636b98ae6b8 <unknown>
#16 0x5636b98ae880 <unknown>
#17 0x5636b98be776 <unknown>
#18 0x7f8953a5aea7 start_thread
; 5253)
[2024-12-20T00:01:32.868+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T00:01:32.888+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
