[2024-12-20T14:01:59.679+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [queued]>
[2024-12-20T14:01:59.689+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [queued]>
[2024-12-20T14:01:59.690+0900] {taskinstance.py:1359} INFO - Starting attempt 4 of 4
[2024-12-20T14:01:59.706+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-18 15:00:00+00:00
[2024-12-20T14:01:59.710+0900] {standard_task_runner.py:57} INFO - Started process 13805 to run task
[2024-12-20T14:01:59.712+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'scheduled__2024-12-18T15:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmp8z09130a']
[2024-12-20T14:01:59.715+0900] {standard_task_runner.py:85} INFO - Job 11: Subtask post_crawl
[2024-12-20T14:01:59.758+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [running]> on host 885d0f0d454c
[2024-12-20T14:01:59.825+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T15:00:00+00:00'
[2024-12-20T14:01:59.826+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-20 14:01:59
[2024-12-20T14:01:59.960+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-20T14:02:00.044+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T14:02:00.129+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T14:02:00.214+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver] found in cache
[2024-12-20T14:02:00.247+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1969, in post_main
    jumpit_crawling()
  File "/code/plugins/post_crawling.py", line 171, in jumpit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x5630cbd268fa <unknown>
#1 0x5630cb837d20 <unknown>
#2 0x5630cb8754c7 <unknown>
#3 0x5630cb86fe8f <unknown>
#4 0x5630cb86af96 <unknown>
#5 0x5630cb8b6d86 <unknown>
#6 0x5630cb8b63d6 <unknown>
#7 0x5630cb8aa893 <unknown>
#8 0x5630cb87930d <unknown>
#9 0x5630cb87a32e <unknown>
#10 0x5630cbcf300b <unknown>
#11 0x5630cbcf6f97 <unknown>
#12 0x5630cbcdf71c <unknown>
#13 0x5630cbcf7b17 <unknown>
#14 0x5630cbcc46cf <unknown>
#15 0x5630cbd156b8 <unknown>
#16 0x5630cbd15880 <unknown>
#17 0x5630cbd25776 <unknown>
#18 0x7f1941335ea7 start_thread

[2024-12-20T14:02:00.262+0900] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241218T150000, start_date=20241220T050159, end_date=20241220T050200
[2024-12-20T14:02:00.274+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task post_crawl (Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x5630cbd268fa <unknown>
#1 0x5630cb837d20 <unknown>
#2 0x5630cb8754c7 <unknown>
#3 0x5630cb86fe8f <unknown>
#4 0x5630cb86af96 <unknown>
#5 0x5630cb8b6d86 <unknown>
#6 0x5630cb8b63d6 <unknown>
#7 0x5630cb8aa893 <unknown>
#8 0x5630cb87930d <unknown>
#9 0x5630cb87a32e <unknown>
#10 0x5630cbcf300b <unknown>
#11 0x5630cbcf6f97 <unknown>
#12 0x5630cbcdf71c <unknown>
#13 0x5630cbcf7b17 <unknown>
#14 0x5630cbcc46cf <unknown>
#15 0x5630cbd156b8 <unknown>
#16 0x5630cbd15880 <unknown>
#17 0x5630cbd25776 <unknown>
#18 0x7f1941335ea7 start_thread
; 13805)
[2024-12-20T14:02:00.288+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T14:02:00.308+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
