[2024-12-19T17:12:12.231+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:10:39+00:00 [queued]>
[2024-12-19T17:12:12.240+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:10:39+00:00 [queued]>
[2024-12-19T17:12:12.241+0900] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-19T17:12:12.254+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-19 08:10:39+00:00
[2024-12-19T17:12:12.260+0900] {standard_task_runner.py:57} INFO - Started process 137 to run task
[2024-12-19T17:12:12.262+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-19T08:10:39+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpj7k1njhg']
[2024-12-19T17:12:12.265+0900] {standard_task_runner.py:85} INFO - Job 4: Subtask post_crawl
[2024-12-19T17:12:12.308+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:10:39+00:00 [running]> on host 3a17ccfe541c
[2024-12-19T17:12:12.377+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T08:10:39+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T08:10:39+00:00'
[2024-12-19T17:12:12.377+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-19 17:12:12
[2024-12-19T17:12:12.474+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:12:12.542+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:12.644+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:12.733+0900] {logger.py:11} INFO - There is no [linux64] chromedriver "131.0.6778.204" for browser google-chrome "131.0.6778" in cache
[2024-12-19T17:12:12.733+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:13.076+0900] {logger.py:11} INFO - WebDriver version 131.0.6778.204 selected
[2024-12-19T17:12:13.079+0900] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T17:12:13.080+0900] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T17:12:13.194+0900] {logger.py:11} INFO - Driver downloading response is 200
[2024-12-19T17:12:13.730+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:13.922+0900] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204]
[2024-12-19T17:12:14.328+0900] {logging_mixin.py:151} INFO - 점핏 종료 시간: 2024-12-19 17:12:14
[2024-12-19T17:12:24.332+0900] {logging_mixin.py:151} INFO - 원티드 시작 시간: 2024-12-19 17:12:24
[2024-12-19T17:12:24.348+0900] {credentials.py:1254} INFO - Found credentials in shared credentials file: /code/.aws/credentials
[2024-12-19T17:12:24.581+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:12:24.646+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:24.717+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:24.826+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:12:25.144+0900] {logging_mixin.py:151} INFO - 원티드 종료 시간: 2024-12-19 17:12:25
[2024-12-19T17:12:25.145+0900] {logging_mixin.py:151} INFO - 인크루트 시작 시간: 2024-12-19 17:12:25
[2024-12-19T17:12:25.807+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:12:25.876+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:25.965+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:26.029+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:12:26.159+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1942, in post_main
    incruit_crawling()
  File "/code/plugins/post_crawling.py", line 623, in incruit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56090cca68fa <unknown>
#1 0x56090c7b7d20 <unknown>
#2 0x56090c7ef438 <unknown>
#3 0x56090c7eaf96 <unknown>
#4 0x56090c836d86 <unknown>
#5 0x56090c8363d6 <unknown>
#6 0x56090c82a893 <unknown>
#7 0x56090c7f930d <unknown>
#8 0x56090c7fa32e <unknown>
#9 0x56090cc7300b <unknown>
#10 0x56090cc76f97 <unknown>
#11 0x56090cc5f71c <unknown>
#12 0x56090cc77b17 <unknown>
#13 0x56090cc446cf <unknown>
#14 0x56090cc956b8 <unknown>
#15 0x56090cc95880 <unknown>
#16 0x56090cca5776 <unknown>
#17 0x7f0cacb48ea7 start_thread

[2024-12-19T17:12:26.167+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241219T081039, start_date=20241219T081212, end_date=20241219T081226
[2024-12-19T17:12:26.180+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task post_crawl (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56090cca68fa <unknown>
#1 0x56090c7b7d20 <unknown>
#2 0x56090c7ef438 <unknown>
#3 0x56090c7eaf96 <unknown>
#4 0x56090c836d86 <unknown>
#5 0x56090c8363d6 <unknown>
#6 0x56090c82a893 <unknown>
#7 0x56090c7f930d <unknown>
#8 0x56090c7fa32e <unknown>
#9 0x56090cc7300b <unknown>
#10 0x56090cc76f97 <unknown>
#11 0x56090cc5f71c <unknown>
#12 0x56090cc77b17 <unknown>
#13 0x56090cc446cf <unknown>
#14 0x56090cc956b8 <unknown>
#15 0x56090cc95880 <unknown>
#16 0x56090cca5776 <unknown>
#17 0x7f0cacb48ea7 start_thread
; 137)
[2024-12-19T17:12:26.206+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-19T17:12:26.225+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
