[2024-12-21T00:29:34.382+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.link_crawl manual__2024-12-20T15:12:27+00:00 [queued]>
[2024-12-21T00:29:34.392+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.link_crawl manual__2024-12-20T15:12:27+00:00 [queued]>
[2024-12-21T00:29:34.392+0900] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-21T00:29:34.410+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): link_crawl> on 2024-12-20 15:12:27+00:00
[2024-12-21T00:29:34.416+0900] {standard_task_runner.py:57} INFO - Started process 2530 to run task
[2024-12-21T00:29:34.419+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'link_crawl', 'manual__2024-12-20T15:12:27+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmparrt7y8m']
[2024-12-21T00:29:34.421+0900] {standard_task_runner.py:85} INFO - Job 20: Subtask link_crawl
[2024-12-21T00:29:34.464+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.link_crawl manual__2024-12-20T15:12:27+00:00 [running]> on host a617ee149c5c
[2024-12-21T00:29:34.557+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='link_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T15:12:27+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T15:12:27+00:00'
[2024-12-21T00:29:34.558+0900] {logging_mixin.py:151} INFO - 인크루트url 시작 시간: 2024-12-21 00:29:34
[2024-12-21T00:29:34.559+0900] {logging_mixin.py:151} INFO - /code/plugins/incruit
[2024-12-21T00:29:42.566+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=0: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:29:50.572+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=30: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:29:58.579+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=60: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=60 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:06.584+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=90: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=90 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:14.591+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=120: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=120 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:22.596+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=150: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=150 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:30.601+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=180: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=180 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:38.607+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=210: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=210 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:46.610+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=240: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=240 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:30:54.615+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=270: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=270 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:02.619+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=300: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=300 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:10.626+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=330: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=330 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:18.633+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=360: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=360 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:26.639+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=390: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=390 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:34.644+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=420: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=420 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:42.650+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=450: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=450 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:50.656+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=480: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=480 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:31:58.662+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=510: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=510 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:06.669+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=540: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=540 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:14.674+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=570: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=570 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:22.680+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=600: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=600 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:30.686+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=630: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=630 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:38.694+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=660: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=660 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:46.700+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=690: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=690 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:32:54.705+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=720: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=720 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:33:02.710+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=750: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=750 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:33:10.717+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=780: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=780 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:33:18.723+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=810: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=810 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:33:26.730+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=840: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=840 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:33:34.735+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=870: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=870 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992f2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:33:42.741+0900] {logging_mixin.py:151} INFO - Error while fetching https://search.incruit.com/list/search.asp?col=job&kw=데이터+엔지니어&startno=900: HTTPSConnectionPool(host='search.incruit.com', port=443): Max retries exceeded with url: /list/search.asp?col=job&kw=%EB%8D%B0%EC%9D%B4%ED%84%B0+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4&startno=900 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4bc992fe50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-12-21T00:34:01.182+0900] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-21T00:34:01.183+0900] {process_utils.py:131} INFO - Sending 15 to group 2530. PIDs of all processes in the group: [2530]
[2024-12-21T00:34:01.183+0900] {process_utils.py:86} INFO - Sending the signal 15 to group 2530
[2024-12-21T00:34:01.184+0900] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-21T00:34:01.192+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/link_crawling.py", line 953, in link_main
    incruit_link()
  File "/code/plugins/link_crawling.py", line 84, in incruit_link
    response = requests.get(url, timeout=20)  # 10초 제한 설정
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-21T00:34:01.202+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=link_crawl, execution_date=20241220T151227, start_date=20241220T152934, end_date=20241220T153401
[2024-12-21T00:34:01.212+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task link_crawl (Task received SIGTERM signal; 2530)
[2024-12-21T00:34:01.236+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=2530, status='terminated', exitcode=1, started='00:29:34') (2530) terminated with exit code 1
